apiVersion: v1
kind: Pod
metadata:
  name: demo-app-pod
  labels:
    app: demo-app
spec:
  containers:
  - name: demo-app
    image: fernandoeick/demo-app-img:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80
